Restore submit_name to QDC 2025 (#286)
We got a user report this morning that this import failed:

```
AttributeError: module 'qc_grader.challenges.qdc_2025.qdc25_lab6' has no attribute 'submit_name'"
```

https://github.com/qiskit-community/Quantum-Challenge-Grader/pull/279
broke them because we removed the duplication functions, with the idea
that people would import `qc_grader.challenges.qdc_2025`. Turns out,
that was wrong. We add back that code.