Improve type validation of qgss_2026 lab0 & document convention (#302)
Closes
https://github.com/qiskit-community/Quantum-Challenge-Grader/issues/293.

Turns out, `typeguard` is already really good at validating that the
user is giving us valid inputs. For example, it understands `list[str]`
vs `list[int]`. The key is that we need to give typeguard good type
hints for it to check things, like `list[int]` rather than `list`.

With dictionaries, we should use `TypedDict` when we need the user to
define specific keys, such as `{"0": 84, "1": 200}`.

I didn't update qdc_2025 because I don't understand that challenge well;
it's also actually doing things pretty well to begin with. The focus is
on making sure we do type validation well in the future.

--

Some example typeguard errors:

```
typeguard.TypeCheckError: item 0 of argument "c_out" (list) is not an instance of str
```
```
typeguard.TypeCheckError: argument "counts" (dict) is missing required key(s): "0", "1"
```
```
typeguard.TypeCheckError: argument "exp_val" (str) did not match any element in the union:
  numpy.ndarray: is not an instance of numpy.ndarray
  float: is neither float or int
```

--

This PR also updates the contributor guide with our expectations for
type validation. It sets up a minimal AGENTS.md to increase the odds
that AI agents follow our expectations.